
services:
  frontend:
    build:
      context: .
    container_name: frontend-service
    hostname: frontendCrea
    ports:
      - "3000:80"
    networks:
      - app-network
  backend:
    build:
      context: ../Efa/CreativaStudio/backend # Reemplaza con la ruta correcta
    container_name: backend-service
    volumes:
      - ../Efa/CreativaStudio/backend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0

networks:
  app-network:
    driver: bridge
